apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  namespace: default
spec:
  type: NodePort  # Change this from LoadBalancer to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Optional: Specify a NodePort (default is assigned)
  selector:
    app: tetris
